# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: updtr

before:
  hooks:
    - go test ./...

builds:
  - id: updtr
    main: .
    binary: updtr
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: archive
    ids:
      - updtr
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc

release:
  github:
    owner: mishankov
    name: updtr
