package action

import (
	"fmt"
	"strings"
	"testing"

	"github.com/mishankov/updtr/internal/config"
	"github.com/mishankov/updtr/internal/core"
)

func TestRenderPullRequestBodyGroupsAppliedUpdatesByTarget(t *testing.T) {
	result := core.RunResult{
		Mode: "apply",
		Targets: []core.TargetResult{
			{
				Target: config.Target{Name: "app", NormalizedPath: "."},
				Applied: []core.AppliedUpdate{
					{
						ModulePath:   "github.com/example/direct",
						FromVersion:  "v1.0.0",
						ToVersion:    "v1.1.0",
						Relationship: core.RelationshipDirect,
					},
					{
						ModulePath:   "github.com/example/indirect",
						FromVersion:  "v0.9.0",
						ToVersion:    "v1.0.0",
						Relationship: core.RelationshipIndirect,
					},
				},
			},
			{
				Target: config.Target{Name: "worker", NormalizedPath: "worker"},
				Applied: []core.AppliedUpdate{{
					ModulePath:   "github.com/example/worker",
					FromVersion:  "v2.0.0",
					ToVersion:    "v2.1.0",
					Relationship: core.RelationshipDirect,
				}},
			},
			{
				Target: config.Target{Name: "noop", NormalizedPath: "noop"},
			},
		},
	}

	body := RenderPullRequestBody(result)
	for _, want := range []string{
		"## Dependency updates",
		"Generated by `updtr`.",
		"- 2 targets updated",
		"- 3 dependency updates updated",
		"## app (.)",
		"`github.com/example/direct`: `v1.0.0` -> `v1.1.0` (direct)",
		"`github.com/example/indirect`: `v0.9.0` -> `v1.0.0` (indirect)",
		"## worker (worker)",
	} {
		if !strings.Contains(body, want) {
			t.Fatalf("body = %q, want %q", body, want)
		}
	}
	if strings.Contains(body, "## noop (noop)") {
		t.Fatalf("body = %q, want targets without applied updates to be omitted", body)
	}
}

func TestRenderPullRequestBodyIncludesVulnerabilitiesAndWarnings(t *testing.T) {
	result := core.RunResult{
		Mode: "apply",
		Targets: []core.TargetResult{{
			Target: config.Target{Name: "app", NormalizedPath: "."},
			Applied: []core.AppliedUpdate{{
				ModulePath:   "github.com/example/mod",
				FromVersion:  "v1.0.0",
				ToVersion:    "v1.1.0",
				Relationship: core.RelationshipDirect,
				Vulnerabilities: []core.Vulnerability{
					{AdvisoryIDs: []string{"GO-2026-0002", "GO-2026-0001"}},
					{AdvisoryIDs: []string{"GO-2026-0002"}},
				},
			}},
			Warnings: []string{core.WarningAdditionalDirectChanges},
		}},
	}

	body := RenderPullRequestBody(result)
	if !strings.Contains(body, "fixes GO-2026-0001, GO-2026-0002") {
		t.Fatalf("body = %q, want sorted advisory identifiers", body)
	}
	if !strings.Contains(body, "## Warnings") {
		t.Fatalf("body = %q, want warnings section", body)
	}
	if !strings.Contains(body, "additional direct dependency changes were detected outside the explicitly applied updates") {
		t.Fatalf("body = %q, want human-readable warning text", body)
	}
}

func TestRenderPullRequestBodyTruncatesLongDetails(t *testing.T) {
	longAdvisories := make([]string, 0, 12)
	for i := 0; i < cap(longAdvisories); i++ {
		longAdvisories = append(longAdvisories, fmt.Sprintf("GO-2026-%04d", i))
	}

	targets := make([]core.TargetResult, 0, 180)
	for i := 0; i < cap(targets); i++ {
		targets = append(targets, core.TargetResult{
			Target: config.Target{
				Name:           fmt.Sprintf("service-%03d-%s", i, strings.Repeat("target", 10)),
				NormalizedPath: fmt.Sprintf("packages/%03d/%s", i, strings.Repeat("nested-path-", 8)),
			},
			Applied: []core.AppliedUpdate{{
				ModulePath:   fmt.Sprintf("github.com/example/%03d/%s", i, strings.Repeat("dependency-segment-", 14)),
				FromVersion:  "v1.0.0",
				ToVersion:    "v1.1.0",
				Relationship: core.RelationshipDirect,
				Vulnerabilities: []core.Vulnerability{{
					AdvisoryIDs: append([]string(nil), longAdvisories...),
				}},
			}},
			Warnings: []string{
				fmt.Sprintf("warning-%03d-%s", i, strings.Repeat("warning-text-", 12)),
			},
		})
	}

	body := RenderPullRequestBody(core.RunResult{Mode: "apply", Targets: targets})
	if len(body) > pullRequestBodyMaxBytes {
		t.Fatalf("body length = %d, want <= %d", len(body), pullRequestBodyMaxBytes)
	}
	if !strings.Contains(body, "and 2 more advisories") {
		t.Fatalf("body = %q, want advisory list compaction", body)
	}
	if !strings.Contains(body, "## Truncated") {
		t.Fatalf("body = %q, want truncated section", body)
	}
	if !strings.Contains(body, "dependency updates omitted") {
		t.Fatalf("body = %q, want omitted update summary", body)
	}
	if !strings.Contains(body, "warnings omitted") {
		t.Fatalf("body = %q, want omitted warning summary", body)
	}
}
