package action

import (
	"fmt"
	"sort"
	"strings"

	"github.com/mishankov/updtr/internal/core"
)

const (
	pullRequestBodyMaxBytes        = 60000
	pullRequestBodyReserveBytes    = 1024
	maxRenderedAdvisoriesPerUpdate = 10
)

func RenderPullRequestBody(result core.RunResult) string {
	targets := appliedTargets(result)
	warnings := bodyWarnings(result)
	detailLimit := pullRequestBodyMaxBytes - pullRequestBodyReserveBytes

	body := &limitedBodyBuilder{limit: pullRequestBodyMaxBytes}
	body.WriteString("## Dependency updates\n\n")
	body.WriteString("Generated by `updtr`.\n\n")
	body.WriteString("## Summary\n\n")
	body.WriteString(fmt.Sprintf("- %s\n", updatedCount(len(targets), "target", "targets")))
	body.WriteString(fmt.Sprintf("- %s\n", updatedCount(countAppliedUpdates(targets), "dependency update", "dependency updates")))

	omittedUpdates := renderAppliedUpdates(body, detailLimit, targets)
	omittedWarnings := renderWarnings(body, detailLimit, warnings)
	if omittedUpdates > 0 || omittedWarnings > 0 {
		body.TryWriteString("\n## Truncated\n\n")
		if omittedUpdates > 0 {
			body.TryWriteString(fmt.Sprintf("- and %d more dependency updates omitted to keep this PR body within GitHub limits\n", omittedUpdates))
		}
		if omittedWarnings > 0 {
			body.TryWriteString(fmt.Sprintf("- and %d more warnings omitted to keep this PR body within GitHub limits\n", omittedWarnings))
		}
	}

	return body.String()
}

func appliedTargets(result core.RunResult) []core.TargetResult {
	out := make([]core.TargetResult, 0, len(result.Targets))
	for _, target := range result.Targets {
		if len(target.Applied) == 0 {
			continue
		}
		out = append(out, target)
	}
	return out
}

func countAppliedUpdates(targets []core.TargetResult) int {
	total := 0
	for _, target := range targets {
		total += len(target.Applied)
	}
	return total
}

func renderUpdateMetadata(update core.AppliedUpdate) string {
	parts := []string{string(relationshipLabel(update.Relationship))}
	advisories := advisoryIDs(update.Vulnerabilities)
	if len(advisories) > 0 {
		parts = append(parts, renderAdvisorySummary(advisories))
	} else if len(update.Vulnerabilities) > 0 {
		parts = append(parts, "includes vulnerability remediation")
	}
	return " (" + strings.Join(parts, "; ") + ")"
}

func renderAppliedUpdates(body *limitedBodyBuilder, limit int, targets []core.TargetResult) int {
	for targetIndex, target := range targets {
		heading := "\n## " + targetLabel(target.Target.Name, target.Target.NormalizedPath) + "\n\n"
		wroteHeading := false
		for updateIndex, update := range target.Applied {
			chunk := renderAppliedUpdateLine(update)
			if !wroteHeading {
				chunk = heading + chunk
			}
			if !body.TryWriteStringWithin(limit, chunk) {
				return remainingAppliedUpdates(targets, targetIndex, updateIndex)
			}
			wroteHeading = true
		}
	}
	return 0
}

func renderAppliedUpdateLine(update core.AppliedUpdate) string {
	return fmt.Sprintf(
		"- `%s`: `%s` -> `%s`%s\n",
		update.ModulePath,
		update.FromVersion,
		update.ToVersion,
		renderUpdateMetadata(update),
	)
}

func remainingAppliedUpdates(targets []core.TargetResult, targetIndex int, updateIndex int) int {
	remaining := 0
	for i := targetIndex; i < len(targets); i++ {
		start := 0
		if i == targetIndex {
			start = updateIndex
		}
		remaining += len(targets[i].Applied[start:])
	}
	return remaining
}

func bodyWarnings(result core.RunResult) []string {
	var warnings []string
	for _, target := range result.Targets {
		for _, warning := range target.Warnings {
			warnings = append(warnings, fmt.Sprintf("%s: %s", targetLabel(target.Target.Name, target.Target.NormalizedPath), warningText(warning)))
		}
	}
	return warnings
}

func warningText(warning string) string {
	switch warning {
	case core.WarningAdditionalDirectChanges:
		return "additional direct dependency changes were detected outside the explicitly applied updates"
	default:
		return warning
	}
}

func advisoryIDs(vulnerabilities []core.Vulnerability) []string {
	seen := map[string]struct{}{}
	var advisories []string
	for _, vulnerability := range vulnerabilities {
		for _, advisory := range vulnerability.AdvisoryIDs {
			if advisory == "" {
				continue
			}
			if _, ok := seen[advisory]; ok {
				continue
			}
			seen[advisory] = struct{}{}
			advisories = append(advisories, advisory)
		}
	}
	sort.Strings(advisories)
	return advisories
}

func renderWarnings(body *limitedBodyBuilder, limit int, warnings []string) int {
	if len(warnings) == 0 {
		return 0
	}

	const heading = "\n## Warnings\n\n"
	wroteHeading := false
	for i, warning := range warnings {
		chunk := "- " + warning + "\n"
		if !wroteHeading {
			chunk = heading + chunk
		}
		if !body.TryWriteStringWithin(limit, chunk) {
			return len(warnings[i:])
		}
		wroteHeading = true
	}
	return 0
}

func renderAdvisorySummary(advisories []string) string {
	visible := advisories
	if len(visible) > maxRenderedAdvisoriesPerUpdate {
		visible = visible[:maxRenderedAdvisoriesPerUpdate]
	}

	summary := "fixes " + strings.Join(visible, ", ")
	if len(visible) == len(advisories) {
		return summary
	}
	return fmt.Sprintf("%s, and %d more advisories", summary, len(advisories)-len(visible))
}

func updatedCount(count int, singular string, plural string) string {
	if count == 1 {
		return fmt.Sprintf("1 %s updated", singular)
	}
	return fmt.Sprintf("%d %s updated", count, plural)
}

func relationshipLabel(relationship core.DependencyRelationship) core.DependencyRelationship {
	if relationship == "" {
		return core.RelationshipDirect
	}
	return relationship
}

func targetLabel(name string, path string) string {
	return fmt.Sprintf("%s (%s)", name, path)
}

type limitedBodyBuilder struct {
	builder strings.Builder
	limit   int
}

func (b *limitedBodyBuilder) String() string {
	return b.builder.String()
}

func (b *limitedBodyBuilder) WriteString(value string) {
	if !b.TryWriteString(value) {
		panic("limitedBodyBuilder.WriteString exceeded PR body limit")
	}
}

func (b *limitedBodyBuilder) TryWriteString(value string) bool {
	if b.builder.Len()+len(value) > b.limit {
		return false
	}
	b.builder.WriteString(value)
	return true
}

func (b *limitedBodyBuilder) TryWriteStringWithin(limit int, value string) bool {
	if limit > b.limit {
		limit = b.limit
	}
	if b.builder.Len()+len(value) > limit {
		return false
	}
	b.builder.WriteString(value)
	return true
}
